name: Set up pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get Application vars
        run: |
          export VERSION=$(python -c "import __init__ as i; print(i.__version__)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Publish to Docker hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: bugcop/pet_project:${{env.VERSION}}-${{ github.run_number }}
